course_discovery/apps/api/urls.py
"""
Root API URLs.

All API URLs should be versioned, so urlpatterns should only
contain namespaces for the active versions of the API.
"""
from django.conf.urls import include, url

urlpatterns = [
    url(r'^v1/', include('course_discovery.apps.api.v1.urls', namespace='v1')),
]

course_discovery/apps/core/urls.py
"""
URLs for the admin autocomplete lookups.
"""
from django.conf.urls import url

from course_discovery.apps.core.lookups import UserAutocomplete

urlpatterns = [
    url(r'^user-autocomplete/$', UserAutocomplete.as_view(), name='user-autocomplete',),
]

course_discovery/apps/publisher/urls.py
"""
URLs for the course publisher views.
"""
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='publisher_dashboard'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),

    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),

    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView


admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=wrong-import-order,wrong-import-position,import-error

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/core/forms.py
""" Core forms. """
from django import forms
from django.utils.translation import ugettext_lazy as _

from course_discovery.apps.core.models import UserThrottleRate


class UserThrottleRateForm(forms.ModelForm):
    """Form for the UserThrottleRate admin."""
    class Meta:
        model = UserThrottleRate
        fields = ('user', 'rate')

    def clean_rate(self):
        rate = self.cleaned_data.get('rate')
        if rate:
            try:
                num, period = rate.split('/')
                int(num)  # Only evaluated for the (possible) side effect of a ValueError
                period_choices = ('second', 'minute', 'hour', 'day')
                if period not in period_choices:
                    # pylint: disable=no-member
                    # Translators: 'period_choices' is a list of possible values, like ('second', 'minute', 'hour')
                    error_msg = _("period must be one of {period_choices}.").format(period_choices=period_choices)
                    raise forms.ValidationError(error_msg)
            except ValueError:
                error_msg = _("'rate' must be in the format defined by DRF, such as '100/hour'.")
                raise forms.ValidationError(error_msg)
        return rate

course_discovery/apps/api/v1/views/affiliates.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from course_discovery.apps.api import serializers
from course_discovery.apps.api.pagination import ProxiedPagination
from course_discovery.apps.api.renderers import AffiliateWindowXMLRenderer
from course_discovery.apps.catalogs.models import Catalog
from course_discovery.apps.course_metadata.models import CourseRun, Seat


class AffiliateWindowViewSet(viewsets.ViewSet):
    """ AffiliateWindow Resource. """
    permission_classes = (IsAuthenticated,)
    renderer_classes = (AffiliateWindowXMLRenderer,)
    serializer_class = serializers.AffiliateWindowSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    def retrieve(self, request, pk=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Return verified and professional seats of courses against provided catalog id.
        ---
        produces:
            - application/xml
        """

        catalog = get_object_or_404(Catalog, pk=pk)

        if not catalog.has_object_read_permission(request):
            raise PermissionDenied

        courses = catalog.courses()
        course_runs = CourseRun.objects.filter(course__in=courses).active().marketable()
        seats = Seat.objects.filter(type__in=[Seat.VERIFIED, Seat.PROFESSIONAL]).filter(course_run__in=course_runs)
        seats = seats.select_related('course_run').prefetch_related('course_run__course', 'course_run__course__partner')

        serializer = serializers.AffiliateWindowSerializer(seats, many=True)
        return Response(serializer.data)

course_discovery/apps/api/v1/views/catalogs.py
import datetime

from django.db import transaction
from django.http import HttpResponse
from dry_rest_permissions.generics import DRYPermissions
from rest_framework import status, viewsets
from rest_framework.decorators import detail_route
from rest_framework.response import Response

from course_discovery.apps.api import filters, serializers
from course_discovery.apps.api.pagination import ProxiedPagination
from course_discovery.apps.api.renderers import CourseRunCSVRenderer
from course_discovery.apps.api.v1.views import User
from course_discovery.apps.catalogs.models import Catalog
from course_discovery.apps.course_metadata.models import CourseRun


# pylint: disable=no-member
class CatalogViewSet(viewsets.ModelViewSet):
    """ Catalog resource. """

    filter_backends = (filters.PermissionsFilter,)
    lookup_field = 'id'
    permission_classes = (DRYPermissions,)
    queryset = Catalog.objects.all()
    serializer_class = serializers.CatalogSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    @transaction.atomic
    def create(self, request, *args, **kwargs):
        """ Create a new catalog. """
        data = request.data.copy()
        usernames = request.data.get('viewers', ())

        # Add support for parsing a comma-separated list from Swagger
        if isinstance(usernames, str):
            usernames = usernames.split(',')
            data.setlist('viewers', usernames)

        # Ensure the users exist
        for username in usernames:
            User.objects.get_or_create(username=username)

        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def destroy(self, request, *args, **kwargs):
        """ Destroy a catalog. """
        return super(CatalogViewSet, self).destroy(request, *args, **kwargs)

    def list(self, request, *args, **kwargs):
        """ Retrieve a list of all catalogs.
        ---
        parameters:
            - name: username
              description: User whose catalogs should be retrieved.
              required: false
              type: string
              paramType: query
              multiple: false
        """
        return super(CatalogViewSet, self).list(request, *args, **kwargs)

    def partial_update(self, request, *args, **kwargs):
        """ Update one, or more, fields for a catalog. """
        return super(CatalogViewSet, self).partial_update(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """ Retrieve details for a catalog. """
        return super(CatalogViewSet, self).retrieve(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        """ Update a catalog. """
        return super(CatalogViewSet, self).update(request, *args, **kwargs)

    @detail_route()
    def courses(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Retrieve the list of courses contained within this catalog.

        Only courses with at least one course run that can be enrolled in immediately,
        is ongoing or yet to start, and appears on the marketing site are returned.
        ---
        serializer: serializers.CatalogCourseSerializer
        """
        catalog = self.get_object()
        queryset = catalog.courses().available()
        course_runs = CourseRun.objects.active().enrollable().marketable()

        queryset = serializers.CatalogCourseSerializer.prefetch_queryset(
            queryset=queryset,
            course_runs=course_runs
        )

        page = self.paginate_queryset(queryset)
        serializer = serializers.CatalogCourseSerializer(page, many=True, context={'request': request})
        return self.get_paginated_response(serializer.data)

    @detail_route()
    def contains(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Determine if this catalog contains the provided courses.

        A dictionary mapping course IDs to booleans, indicating course presence, will be returned.
        ---
        serializer: serializers.ContainedCoursesSerializer
        parameters:
            - name: course_id
              description: Course IDs to check for existence in the Catalog.
              required: true
              type: string
              paramType: query
              multiple: true
            - name: course_run_id
              description: Course run IDs to check for existence in the Catalog.
              required: false
              type: string
              paramType: query
              multiple: true
        """
        course_ids = request.query_params.get('course_id')
        course_run_ids = request.query_params.get('course_run_id')

        catalog = self.get_object()
        courses = {}
        if course_ids:
            course_ids = course_ids.split(',')
            courses.update(catalog.contains(course_ids))

        if course_run_ids:
            course_run_ids = course_run_ids.split(',')
            courses.update(catalog.contains_course_runs(course_run_ids))

        instance = {'courses': courses}
        serializer = serializers.ContainedCoursesSerializer(instance)
        return Response(serializer.data)

    @detail_route()
    def csv(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Retrieve a CSV containing the course runs contained within this catalog.

        Only active course runs are returned. A course run is considered active if it is currently
        open for enrollment, or will be open for enrollment in the future.
        ---
        serializer: serializers.FlattenedCourseRunWithCourseSerializer
        """
        catalog = self.get_object()
        courses = catalog.courses()
        course_runs = CourseRun.objects.filter(course__in=courses).active().marketable()

        # We use select_related and prefetch_related to decrease our database query count
        course_runs = course_runs.select_related(*serializers.SELECT_RELATED_FIELDS['course_run'])
        prefetch_fields = ['course__' + field for field in serializers.PREFETCH_FIELDS['course']]
        prefetch_fields += serializers.PREFETCH_FIELDS['course_run']
        course_runs = course_runs.prefetch_related(*prefetch_fields)

        serializer = serializers.FlattenedCourseRunWithCourseSerializer(
            course_runs, many=True, context={'request': request}
        )
        data = CourseRunCSVRenderer().render(serializer.data)

        response = HttpResponse(data, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="catalog_{id}_{date}.csv"'.format(
            id=id, date=datetime.datetime.utcnow().strftime('%Y-%m-%d-%H-%M')
        )
        return response

course_discovery/apps/api/v1/views/organizations.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from course_discovery.apps.api import filters, serializers
from course_discovery.apps.api.pagination import ProxiedPagination


# pylint: disable=no-member
class OrganizationViewSet(viewsets.ReadOnlyModelViewSet):
    """ Organization resource. """

    filter_backends = (DjangoFilterBackend,)
    filter_class = filters.OrganizationFilter
    lookup_field = 'uuid'
    lookup_value_regex = '[0-9a-f-]+'
    permission_classes = (IsAuthenticated,)
    queryset = serializers.OrganizationSerializer.prefetch_queryset()
    serializer_class = serializers.OrganizationSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    def list(self, request, *args, **kwargs):
        """ Retrieve a list of all organizations. """
        return super(OrganizationViewSet, self).list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """ Retrieve details for an organization. """
        return super(OrganizationViewSet, self).retrieve(request, *args, **kwargs)

course_discovery/apps/api/v1/views/program_types.py
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated

from course_discovery.apps.api import serializers
from course_discovery.apps.course_metadata.models import ProgramType


class ProgramTypeViewSet(viewsets.ReadOnlyModelViewSet):
    """ ProgramType resource. """
    lookup_field = 'slug'
    pagination_class = PageNumberPagination
    permission_classes = (IsAuthenticated,)
    queryset = serializers.ProgramTypeSerializer.prefetch_queryset(ProgramType.objects.all())
    serializer_class = serializers.ProgramTypeSerializer

course_discovery/templates/publisher/dashboard/_in_preview.html
{% load i18n %}
{% if preview_count == 0 %}
    <div class="empty-courserun-text">{% trans "No course runs currently have an About page preview available for course team review." %}</div>
{% else %}
    <p>
        {% trans "About page previews for the following course runs are available for course team review. After the course team approves the preview, the edX publisher will publish the About page for the course run on edx.org. The course team will receive an email message when the About page has been published." %}
    </p>
    <div class="table-view">
        <table class="data-table-preview display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th role="button">
                        {% trans "Course Name" %}
                    </th>
                    <th role="button">
                        {% trans "Organization" %}
                    </th>
                    <th role="button">
                        {% trans "Status" %}
                    </th>
                    <th>
                        {% trans "Course start date" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for course_run in preview_course_runs %}
                    <tr>
                        <td id="course-title-{{ course_run.title }}">
                            <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">{{ course_run.title }}</a>
                            <br>
                            <a target="_blank" href="{{ course_run.preview_url }}">{{ course_run.preview_url }}</a>
                        </td>
                        <td>
                        {{ course_run.course.organization_name }}
                        </td>
                        <td>
                            {% if course_run.course_run_state.preview_accepted %}
                                {% trans "Approved since " %}
                            {% elif course_run.preview_declined and not course_run.preview_url %}
                                {% trans "Declined since " %}
                            {% elif not course_run.preview_url %}
                                {% trans "Preview Requested since " %}
                            {% else %}
                                {% trans "In Review since " %}
                            {% endif %}
                            {{ course_run.owner_role_modified }}
                        </td>
                        <td>
                            {{ course_run.start }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

course_discovery/templates/publisher/dashboard/_in_progress.html
{% load i18n %}
{% if in_progress_count == 0 %}
    <div class="empty-courserun-text">{% trans "No About pages for any course runs are currently in development." %}</div>
{% else %}
    <table class="data-table-in-progress display" cellspacing="0" width="100%">
        <div class="filters">
            <strong>{% trans "Filter by" %}:</strong>
            <button type="button" class="btn-neutral btn-small btn-filter active" data-filter-column="-1">{% trans "All" %}
                <span class="filter-count">{{ in_progress_count }}</span>
            </button>
            <button type="button" class="btn-neutral btn-small btn-filter" data-filter-column="5">{% trans "With Course Team" %}
                <span class="filter-count">{{ course_team_count }}</span>
            </button>
            <button type="button" class="btn-neutral btn-small btn-filter" data-filter-column="6">{% trans "With" %} {{ site_name }}
                <span class="filter-count">{{ internal_user_count }}</span>
            </button>
        </div>
        <thead>
            <tr>
                <th role="button">
                    {% trans "Course Name" %}
                </th>
                <th role="button">
                    {% trans "Course Number" %}
                </th>
                <th role="button">
                    {% trans "Organization" %}
                </th>
                <th role="button">
                    {% trans "Start" %}
                </th>
                <th role="button">
                    {% trans "End" %}
                </th>
                <th role="button">
                    {% trans "Course Team" %}
                </th>
                <th role="button">
                    {{ site_name }}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for course_run in in_progress_course_runs %}
                <tr>
                    <td>
                        <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">{{ course_run.title }}</a>
                    </td>
                    <td>
                        {{ course_run.number }}
                    </td>
                    <td>
                        {{ course_run.course.organization_name }}
                    </td>
                    <td>
                         {{ course_run.start|date:"Y-m-d" }}
                    </td>
                    <td>
                        {{ course_run.end|date:"Y-m-d" }}
                    </td>
                    <td>
                        {{ course_run.course_team_status.status_text }}<br>
                        {{ course_run.course_team_status.date|date:'m/d/y' }}
                    </td>
                    <td>
                        {{ course_run.internal_user_status.status_text }}<br>
                        {{ course_run.internal_user_status.date|date:'m/d/y' }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

course_discovery/templates/publisher/dashboard/_published.html
{% load i18n %}
{% if published_count == 0 %}
    <div class="empty-courserun-text">{% trans "No About pages have been published yet." %}</div>
{% else %}
    <p>
        {% blocktrans trimmed %}
            About pages for the following course runs have been published in the past {{ default_published_days }} days.
        {% endblocktrans %}
    </p>
    <table class="data-table-published display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th role="button">
                    {% trans "Course Name" %}
                </th>
                <th role="button">
                    {% trans "Course Number" %}
                </th>
                <th role="button">
                    {% trans "Organization" %}
                </th>
                <th role="button">
                    {% trans "Start" %}
                </th>
                <th role="button">
                    {% trans "End" %}
                </th>
                <th role="button">
                    {% trans "Published Date" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for course_run in published_course_runs %}
                <tr>
                    <td>
                        <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">{{ course_run.title }}</a>
                    </td>
                    <td>
                        {{ course_run.number }}
                    </td>
                    <td>
                        {{ course_run.course.organization_name }}
                    </td>
                    <td>
                         {{ course_run.start|date:"Y-m-d" }}
                    </td>
                    <td>
                        {{ course_run.end|date:"Y-m-d" }}
                    </td>
                    <td>
                        {{ course_run.course_run_state.modified|date:"Y-m-d" }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

course_discovery/templates/publisher/dashboard/_studio_requests.html
{% load i18n %}

{% if studio_count > 0 %}
    <p>{% trans "The following courses are ready for a Studio URL." %}</p>
        <div class="studio-instance-success depth depth-0">
          <p class="copy-meta"></p>
        </div>
        <div class="alert alert-error alert-slim studio-instance-error hidden">
            <div class="alert-message">
                <p class="copy"></p>
            </div>
        </div>
    <div class="table-view">
        <table class="data-table-studio display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th role="button">
                        {% trans "Course Name" %}
                    </th>
                    <th role="button">
                        {% trans "Organization" %}
                    </th>
                    <th role="button">
                        {% trans "Start Date" %}
                    </th>
                    <th role="button">
                        {% trans "Course Number" %}
                    </th>
                    <th id="column-title" role="button">
                        {% trans "Studio Course Run Key" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for course_run in studio_request_courses %}
                    <tr>
                        {% url 'publisher:publisher_course_run_detail' course_run.id as run_page_url %}
                            <td id="course-title-{{ course_run.title }}">
                                <a href="{{ run_page_url }}" id="course-title">{{ course_run.title }}</a>
                            </td>
                            <td>
                                {{ course_run.course.organization_name }}
                            </td>
                            <td id="course-start">
                                 {{ course_run.start|date:"Y-m-d" }}
                            </td>
                            <td>
                                {{ course_run.number }}
                            </td>
                            <td class="form-group">
                                <input type="text" class="field-input input-text small" aria-labelledby="course-title-{{ course_run.title }} column-title" />
                                <button data-update-course-key-url="{% url 'publisher:api:update_course_run' course_run.id %}" class="btn-inline btn-add-course-key">{% trans "Add" %}</button>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% else %}
    <div class="empty-courserun-text">{% trans "No courses are currently ready for a Studio URL." %}</div>
{% endif %}