course_discovery/apps/api/urls.py
"""
Root API URLs.

All API URLs should be versioned, so urlpatterns should only
contain namespaces for the active versions of the API.
"""
from django.conf.urls import include, url

urlpatterns = [
    url(r'^v1/', include('course_discovery.apps.api.v1.urls', namespace='v1')),
]

course_discovery/apps/core/urls.py
"""
URLs for the admin autocomplete lookups.
"""
from django.conf.urls import url

from course_discovery.apps.core.lookups import UserAutocomplete

urlpatterns = [
    url(r'^user-autocomplete/$', UserAutocomplete.as_view(), name='user-autocomplete',),
]

course_discovery/apps/publisher/urls.py
"""
URLs for the course publisher views.
"""
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='publisher_dashboard'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),

    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),

    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView


admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=wrong-import-order,wrong-import-position,import-error

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/course_metadata/models.py
import datetime
import itertools
import logging
from collections import defaultdict
from urllib.parse import urljoin
from uuid import uuid4

import pytz
import waffle
from django.db import models, transaction
from django.db.models.query_utils import Q
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField
from django_extensions.db.models import TimeStampedModel
from haystack.query import SearchQuerySet
from solo.models import SingletonModel
from sortedm2m.fields import SortedManyToManyField
from stdimage.models import StdImageField
from stdimage.utils import UploadToAutoSlug
from taggit_autosuggest.managers import TaggableManager

from course_discovery.apps.core.models import Currency, Partner
from course_discovery.apps.course_metadata.choices import CourseRunPacing, CourseRunStatus, ProgramStatus, ReportingType
from course_discovery.apps.course_metadata.publishers import (
    CourseRunMarketingSitePublisher,
    ProgramMarketingSitePublisher
)
from course_discovery.apps.course_metadata.query import CourseQuerySet, CourseRunQuerySet, ProgramQuerySet
from course_discovery.apps.course_metadata.utils import UploadToFieldNamePath, clean_query, custom_render_variations
from course_discovery.apps.ietf_language_tags.models import LanguageTag

logger = logging.getLogger(__name__)


class AbstractNamedModel(TimeStampedModel):
    """ Abstract base class for models with only a name field. """
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta(object):
        abstract = True


class AbstractValueModel(TimeStampedModel):
    """ Abstract base class for models with only a value field. """
    value = models.CharField(max_length=255)

    def __str__(self):
        return self.value

    class Meta(object):
        abstract = True


class AbstractMediaModel(TimeStampedModel):
    """ Abstract base class for media-related (e.g. image, video) models. """
    src = models.URLField(max_length=255, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.src

    class Meta(object):
        abstract = True


class AbstractSocialNetworkModel(TimeStampedModel):
    """ SocialNetwork model. """
    FACEBOOK = 'facebook'
    TWITTER = 'twitter'
    BLOG = 'blog'
    OTHERS = 'others'

    SOCIAL_NETWORK_CHOICES = (
        (FACEBOOK, _('Facebook')),
        (TWITTER, _('Twitter')),
        (BLOG, _('Blog')),
        (OTHERS, _('Others')),
    )

    type = models.CharField(max_length=15, choices=SOCIAL_NETWORK_CHOICES, db_index=True)
    value = models.CharField(max_length=500)

    def __str__(self):
        return '{type}: {value}'.format(type=self.type, value=self.value)

    class Meta(object):
        abstract = True


class Image(AbstractMediaModel):
    """ Image model. """
    height = models.IntegerField(null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)


class Video(AbstractMediaModel):
    """ Video model. """
    image = models.ForeignKey(Image, null=True, blank=True)

    def __str__(self):
        return '{src}: {description}'.format(src=self.src, description=self.description)


class LevelType(AbstractNamedModel):
    """ LevelType model. """
    pass


class Subject(TimeStampedModel):
    """ Subject model. """
    uuid = models.UUIDField(blank=False, null=False, default=uuid4, editable=False, verbose_name=_('UUID'))
    name = models.CharField(max_length=255, blank=False, null=False)
    subtitle = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    banner_image_url = models.URLField(blank=True, null=True)
    card_image_url = models.URLField(blank=True, null=True)
    slug = AutoSlugField(populate_from='name', editable=True, blank=True,
                         help_text=_('Leave this field blank to have the value generated automatically.'))
    partner = models.ForeignKey(Partner)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (
            ('partner', 'name'),
            ('partner', 'slug'),
            ('partner', 'uuid'),
        )


class Prerequisite(AbstractNamedModel):
    """ Prerequisite model. """
    pass


class ExpectedLearningItem(AbstractValueModel):
    """ ExpectedLearningItem model. """
    pass


class JobOutlookItem(AbstractValueModel):
    """ JobOutlookItem model. """
    pass


class SyllabusItem(AbstractValueModel):
    """ SyllabusItem model. """
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children')


class Organization(TimeStampedModel):
    """ Organization model. """
    partner = models.ForeignKey(Partner, null=True, blank=False)
    uuid = models.UUIDField(blank=False, null=False, default=uuid4, editable=False, verbose_name=_('UUID'))
    key = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    marketing_url_path = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    homepage_url = models.URLField(max_length=255, null=True, blank=True)
    logo_image_url = models.URLField(null=True, blank=True)
    banner_image_url = models.URLField(null=True, blank=True)
    certificate_logo_image_url = models.URLField(
        null=True, blank=True, help_text=_('Logo to be displayed on certificates. If this logo is the same as '
                                           'logo_image_url, copy and paste the same value to both fields.')
    )

    tags = TaggableManager(
        blank=True,
        help_text=_('Pick a tag from the suggestions. To make a new tag, add a comma after the tag name.'),
    )

    class Meta:
        unique_together = (
            ('partner', 'key'),
            ('partner', 'uuid'),
        )

    def __str__(self):
        return '{key}: {name}'.format(key=self.key, name=self.name)

    @property
    def marketing_url(self):
        if self.marketing_url_path:
            return urljoin(self.partner.marketing_site_url_root, self.marketing_url_path)

        return None


class Person(TimeStampedModel):
    """ Person model. """
    uuid = models.UUIDField(blank=False, null=False, default=uuid4, editable=False, verbose_name=_('UUID'))
    partner = models.ForeignKey(Partner, null=True, blank=False)
    given_name = models.CharField(max_length=255)
    family_name = models.CharField(max_length=255, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image_url = models.URLField(null=True, blank=True)
    profile_image = StdImageField(
        upload_to=UploadToAutoSlug(populate_from='uuid', path='media/people/profile_images'),
        blank=True,
        null=True,
        variations={
            'medium': (110, 110),
        },
    )
    slug = AutoSlugField(populate_from=('given_name', 'family_name'), editable=True)
    profile_url = models.URLField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True, max_length=255)

    class Meta:
        unique_together = (
            ('partner', 'uuid'),
        )
        verbose_name_plural = _('People')

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return ' '.join((self.given_name, self.family_name,))

    @property
    def get_profile_image_url(self):
        url = self.profile_image_url
        if not url:
            if self.profile_image and hasattr(self.profile_image, 'url'):
                url = self.profile_image.url

        return url


class Position(TimeStampedModel):
    """ Position model.

    This model represent's a `Person`'s role at an organization.
    """
    person = models.OneToOneField(Person)
    title = models.CharField(max_length=255)
    organization = models.ForeignKey(Organization, null=True, blank=True)
    organization_override = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return '{title} at {organization}'.format(title=self.title, organization=self.organization_name)

    @property
    def organization_name(self):
        name = self.organization_override

        if self.organization and not name:
            name = self.organization.name

        return name


class Course(TimeStampedModel):
    """ Course model. """
    partner = models.ForeignKey(Partner)
    uuid = models.UUIDField(default=uuid4, editable=False, verbose_name=_('UUID'))
    canonical_course_run = models.OneToOneField(
        'course_metadata.CourseRun', related_name='canonical_for_course', default=None, null=True, blank=True
    )
    key = models.CharField(max_length=255)
    title = models.CharField(max_length=255, default=None, null=True, blank=True)
    short_description = models.CharField(max_length=255, default=None, null=True, blank=True)
    full_description = models.TextField(default=None, null=True, blank=True)
    authoring_organizations = SortedManyToManyField(Organization, blank=True, related_name='authored_courses')
    sponsoring_organizations = SortedManyToManyField(Organization, blank=True, related_name='sponsored_courses')
    subjects = models.ManyToManyField(Subject, blank=True)
    prerequisites = models.ManyToManyField(Prerequisite, blank=True)
    level_type = models.ForeignKey(LevelType, default=None, null=True, blank=True)
    expected_learning_items = SortedManyToManyField(ExpectedLearningItem, blank=True)
    card_image_url = models.URLField(null=True, blank=True)
    slug = AutoSlugField(populate_from='key', editable=True)
    video = models.ForeignKey(Video, default=None, null=True, blank=True)
    number = models.CharField(
        max_length=50, null=True, blank=True, help_text=_(
            'Course number format e.g CS002x, BIO1.1x, BIO1.2x'
        )
    )

    objects = CourseQuerySet.as_manager()

    class Meta:

course_discovery/apps/ietf_language_tags/models.py
""" IETF language tag models. """

from django.db import models


class LanguageTag(models.Model):
    """ Table of language tags as defined by BCP 47. https://tools.ietf.org/html/bcp47 """
    code = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    @property
    def macrolanguage(self):
        return self.name.split('-')[0].strip()

course_discovery/apps/publisher_comments/models.py
import logging
import waffle
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from django_comments.models import CommentAbstractModel
from django_extensions.db.fields import ModificationDateTimeField
from djchoices import ChoiceItem, DjangoChoices

from course_discovery.apps.publisher.choices import PublisherUserRole
from course_discovery.apps.publisher_comments.emails import send_email_decline_preview, send_email_for_comment

log = logging.getLogger(__name__)


class CommentTypeChoices(DjangoChoices):
    Default = ChoiceItem('default', _('Default'))
    Decline_Preview = ChoiceItem('decline_preview', _('Decline Preview'))


class Comments(CommentAbstractModel):
    DEFAULT = 'default'
    DECLINE_PREVIEW = 'decline_preview'

    modified = ModificationDateTimeField(_('modified'))

    # comment type added to differentiate weather comment is for preview decline or a
    # normal comment on content of course/course run.
    comment_type = models.CharField(
        max_length=255, null=True, blank=True, choices=CommentTypeChoices.choices, default=CommentTypeChoices.Default
    )

    def save(self, *args, **kwargs):
        if self.comment_type == CommentTypeChoices.Decline_Preview:
            try:
                mark_preview_url_as_decline(self)
            except Exception:  # pylint: disable=broad-except
                # in case of exception don't save the comment
                return
        else:
            if waffle.switch_is_active('enable_publisher_email_notifications'):
                created = False if self.id else True
                send_email_for_comment(self, created)

        super(Comments, self).save(*args, **kwargs)


@transaction.atomic
def mark_preview_url_as_decline(instance):
    course_run = instance.content_type.get_object_for_this_type(pk=instance.object_pk)

    # remove the preview url
    preview_url = course_run.preview_url
    course_run.preview_url = None
    course_run.save()

    # assign course back to publisher
    course_run.course_run_state.change_owner_role(PublisherUserRole.Publisher)

    # send email for decline preview to publisher
    if waffle.switch_is_active('enable_publisher_email_notifications'):
        send_email_decline_preview(instance, course_run, preview_url)

course_discovery/templates/publisher/_breadcrumbs.html
{% if breadcrumbs %}
    <ol class="breadcrumb">
      {% for breadcrumb in breadcrumbs %}
        <li class="breadcrumb-item {% if forloop.last %}active{% endif %}">
            {% if forloop.last %}
                {{ breadcrumb.slug }}
            {% else %}
                <a href="{{ breadcrumb.url }}">{{ breadcrumb.slug }}</a>
            {% endif %}
        </li>
      {% endfor %}
    </ol>
{% endif %}

course_discovery/templates/publisher/_clearImageLink.html
<div class="clear-image">
    <a class="remove-image" href="#">%(clear_checkbox_label)s</a>
    <div class="hidden">%(clear)s</div>
</div>

course_discovery/templates/publisher/_clearableImageInput.html
<img class="course-image-thumbnail" src="%(initial_url)s">%(clear_template)s
<div class="course-image-input hidden">%(input)s</div>

course_discovery/templates/publisher/_header.html
{% load static %}
{% load i18n %}
<header class="header">
    <div class="layout-1q1h1q layout-flush layout-header">
        <nav class="layout-col layout-col-a">
            <a href="{% url 'publisher:publisher_dashboard' %}">
                <img src="{% static 'images/logo.png' %}">
            </a>
        </nav>

        <main class="layout-col layout-col-b"></main>

        <aside class="layout-col layout-col-c">
            <nav class="nav-account" aria-label="{% trans 'Account' %}">
                <h2 class="sr-only">{% trans "Account Navigation" %}</h2>
                <ol>
                    <li class="nav-item nav-account-help">
                        <h3 class="title">
                            <span class="label">
                                <a href="https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/set_up_course/pub_create_ann_course/index.html" title="{% trans 'Contextual Online Help' %}" target="_blank">
                                    {% trans "Help" %}
                                </a>
                            </span>
                        </h3>
                    </li>
                    <li class="nav-item nav-account-user">
                        <h3 class="title">
                            <span class="label">
                                <a href="#" title="{{ user.username }}">{{ user.username|truncatechars:10 }}</a>
                            </span>
                            <span class="icon fa fa-caret-down"></span>
                        </h3>
                    </li>
                </ol>

                <div class="wrapper wrapper-nav-sub">
                    <div class="nav-sub">
                        <div class="nav-menu-item nav-email-notification">
                            <span class="email-switch-label"><b>{% trans "Email notifications" %}</b></span>
                            <label class="switch">
                                <input id="email-switch" type="checkbox" data-isEnabled="{{ is_email_notification_enabled }}" {% if is_email_notification_enabled %}checked{% endif %}>
                                <div class="slider"></div>
                            </label>
                            <span class="switch-label">{% if is_email_notification_enabled %} {% trans "ON" %} {% else %} {% trans "OFF" %} {% endif %}</span>
                        </div>
                        <div class="nav-menu-item nav-account-signout">
                            <a class="btn-neutral" href="/logout">{% trans "Sign Out" %}</a>
                        </div>
                    </div>
                </div>
            </nav>
        </aside>
    </div>
</header>

course_discovery/templates/publisher/course_detail.html
{% extends 'publisher/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}
    {% trans "Course Detail" %}
{% endblock title %}

{% block page_content %}
{% include 'alert_messages.html' %}

<div id="stateChangeAlert" class="alert-messages hidden">
    <div class="alert alert-error" role="alert" tabindex="-1">
        <div>
            <p id="stateChangeError" class="alert-copy"></p>
        </div>
    </div>
</div>


<div class="layout-1t2t layout-flush publisher-container course-detail">
    <main class="layout-col layout-col-b layout-col-b-custom">
        <div class="course-information">

        <div class="edit-history-widget">
            {% with object.history.all as history_list %}
                {% if history_list.count > 1 %}
                    <div class="history-widget {% if not publisher_history_widget_feature %}hidden{% endif %}">
                        {% include 'publisher/_history_widget.html' %}
                    </div>
                {% endif %}
            {% endwith %}

            {% if can_edit %}
                {% url 'publisher:publisher_courses_edit' pk=object.id as edit_page_url %}
                <a id="btn_course_edit" href="{% if add_warning_popup %}#{% else %}{{ edit_page_url }}{% endif %}" class="btn btn-neutral btn-course-edit">
                    {% trans "EDIT" %}
                </a>
                <div class="clearfix"></div>
            {% endif %}
        </div>

            <div class="info-item">
                <div class="heading">
                    {% trans "Organization Name" %}
                </div>
                <div>
                    {{ object.organizations.first }}
                </div>
            </div>

            <div class="info-item">
                <div class="heading">
                    {% trans "Course Team Admin" %}
                </div>
                <div>{{ object.course_team_admin.full_name }}</div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Course Title" %}
                </div>
                <div class="current title">{{ object.course_title }}</div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Course Number" %}
                </div>
                <div class="current number">{{ object.number }}</div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Short Description" %}
                </div>
                <div class="current short_description">
                    {% with  object.course_short_description as field %}
                        {% include "publisher/_render_required_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Long Description" %}
                </div>
                <div class="current full_description">
                    {% with  object.course_full_description as field %}
                        {% include "publisher/_render_required_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "What You Will Learn" %}
                </div>
                <div class="current expected_learnings">
                    {% with  object.expected_learnings as field %}
                        {% include "publisher/_render_required_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Primary Subject" %}
                </div>
                <div class="current primary_subject">
                    {% with  object.primary_subject as field %}
                        {% include "publisher/_render_required_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Additional Subject" %}
                </div>
                <div class="current secondary_subject">
                    {% with  object.secondary_subject as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Additional Subject" %}
                </div>
                <div class="current tertiary_subject">
                    {% with  object.tertiary_subject as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>
            <div class="info-item">
                <div class="heading course-image-heading">
                    {% trans "Course Image" %}
                </div>
                {% if object.course_image_url %}
                    <img class="course-image" src="{{ object.course_image_url }}" alt="{% trans 'Course Image' %}">
                {% else %}
                    {% trans "(Required) Not yet added" %}
                {% endif %}
            </div>
            <div class="info-item history-field-container">
                <div class="heading">
                    {% trans "Prerequisites" %}
                </div>
                <div class="current prerequisites">
                    {% with  object.prerequisites as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>
            <div class="info-item history-field-container">
                <div class="heading">{% trans "Course Level" %}
                </div>
                <div class="current level_type">
                    {% with  object.level_type as field %}
                        {% include "publisher/_render_required_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>
            <div class="info-item history-field-container">
                <div class="heading">{% trans "Learner Testimonials" %}
                </div>
                <div class="current learner_testimonial">
                    {% with  object.learner_testimonial as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>
            <div class="info-item history-field-container">
                <div class="heading">{% trans "FAQ" %}
                </div>
                <div class="current faq">
                    {% with  object.faq as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">{% trans "Syllabus" %}
                </div>
                <div class="current faq">
                    {% with  object.syllabus as field %}
                        {% include "publisher/_render_optional_field.html" %}
                    {% endwith %}
                </div>
                <div class="show-diff"></div>
            </div>

            <div class="info-item history-field-container">
                <div class="heading">{% trans "About Video Link" %}
                </div>
                {% with  object.video_link as value %}
                    {% if value %}
                        <a class="current video_link" href="{{ value }}" target="_blank">{{ value }}</a>
                    {% else %}
                        {% trans "(Optional) Not yet added" %}
                    {% endif %}
                {% endwith %}
                <div class="show-diff"></div>
            </div>
        </div>
    </main>

    <aside id="right-panel" class="layout-col layout-col-a layout-col-a-custom">
        <div id="approval-widget" class="{% if publisher_hide_features_for_pilot %}hidden{% endif %}">
            {% include 'publisher/course_detail/_widgets.html' %}
        </div>
        <div id="comments-widget" class="comment-container {% if not publisher_comment_widget_feature %}hidden{% endif %}">
            {% include 'comments/add_auth_comments.html' %}
            {% include 'comments/comments_list.html' %}
        </div>
    </aside>
</div>
{% endblock %}
{% block extra_js %}
    <script src="{% static 'bower_components/google-diff-match-patch/diff_match_patch.js' %}"></script>
    <script src="{% static 'js/publisher/decode-html.js' %}"></script>
    <script src="{% static 'js/publisher/views/course_detail.js' %}"></script>
    <script src="{% static 'js/publisher/organizations.js' %}"></script>
    <script src="{% static 'js/publisher/comparing-objects.js' %}"></script>
    <script src="{% static 'js/publisher/jquery-dateFormat.min.js' %}"></script>
    <script src="{% static 'js/publisher/comments.js' %}"></script>
    <script src="{% static 'js/publisher/change-state.js' %}"></script>
    <script src="{% static 'js/publisher/revision-history.js' %}"></script>
    <script src="{% static 'js/publisher/modal-screen.js' %}"></script>
{% endblock %}