course_discovery/apps/api/urls.py
"""
Root API URLs.

All API URLs should be versioned, so urlpatterns should only
contain namespaces for the active versions of the API.
"""
from django.conf.urls import include, url

urlpatterns = [
    url(r'^v1/', include('course_discovery.apps.api.v1.urls', namespace='v1')),
]

course_discovery/apps/core/urls.py
"""
URLs for the admin autocomplete lookups.
"""
from django.conf.urls import url

from course_discovery.apps.core.lookups import UserAutocomplete

urlpatterns = [
    url(r'^user-autocomplete/$', UserAutocomplete.as_view(), name='user-autocomplete',),
]

course_discovery/apps/publisher/urls.py
"""
URLs for the course publisher views.
"""
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='publisher_dashboard'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),

    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),

    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView


admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=wrong-import-order,wrong-import-position,import-error

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/publisher_comments/models.py
import logging
import waffle
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from django_comments.models import CommentAbstractModel
from django_extensions.db.fields import ModificationDateTimeField
from djchoices import ChoiceItem, DjangoChoices

from course_discovery.apps.publisher.choices import PublisherUserRole
from course_discovery.apps.publisher_comments.emails import send_email_decline_preview, send_email_for_comment

log = logging.getLogger(__name__)


class CommentTypeChoices(DjangoChoices):
    Default = ChoiceItem('default', _('Default'))
    Decline_Preview = ChoiceItem('decline_preview', _('Decline Preview'))


class Comments(CommentAbstractModel):
    DEFAULT = 'default'
    DECLINE_PREVIEW = 'decline_preview'

    modified = ModificationDateTimeField(_('modified'))

    # comment type added to differentiate weather comment is for preview decline or a
    # normal comment on content of course/course run.
    comment_type = models.CharField(
        max_length=255, null=True, blank=True, choices=CommentTypeChoices.choices, default=CommentTypeChoices.Default
    )

    def save(self, *args, **kwargs):
        if self.comment_type == CommentTypeChoices.Decline_Preview:
            try:
                mark_preview_url_as_decline(self)
            except Exception:  # pylint: disable=broad-except
                # in case of exception don't save the comment
                return
        else:
            if waffle.switch_is_active('enable_publisher_email_notifications'):
                created = False if self.id else True
                send_email_for_comment(self, created)

        super(Comments, self).save(*args, **kwargs)


@transaction.atomic
def mark_preview_url_as_decline(instance):
    course_run = instance.content_type.get_object_for_this_type(pk=instance.object_pk)

    # remove the preview url
    preview_url = course_run.preview_url
    course_run.preview_url = None
    course_run.save()

    # assign course back to publisher
    course_run.course_run_state.change_owner_role(PublisherUserRole.Publisher)

    # send email for decline preview to publisher
    if waffle.switch_is_active('enable_publisher_email_notifications'):
        send_email_decline_preview(instance, course_run, preview_url)

course_discovery/apps/api/v1/views/affiliates.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from course_discovery.apps.api import serializers
from course_discovery.apps.api.pagination import ProxiedPagination
from course_discovery.apps.api.renderers import AffiliateWindowXMLRenderer
from course_discovery.apps.catalogs.models import Catalog
from course_discovery.apps.course_metadata.models import CourseRun, Seat


class AffiliateWindowViewSet(viewsets.ViewSet):
    """ AffiliateWindow Resource. """
    permission_classes = (IsAuthenticated,)
    renderer_classes = (AffiliateWindowXMLRenderer,)
    serializer_class = serializers.AffiliateWindowSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    def retrieve(self, request, pk=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Return verified and professional seats of courses against provided catalog id.
        ---
        produces:
            - application/xml
        """

        catalog = get_object_or_404(Catalog, pk=pk)

        if not catalog.has_object_read_permission(request):
            raise PermissionDenied

        courses = catalog.courses()
        course_runs = CourseRun.objects.filter(course__in=courses).active().marketable()
        seats = Seat.objects.filter(type__in=[Seat.VERIFIED, Seat.PROFESSIONAL]).filter(course_run__in=course_runs)
        seats = seats.select_related('course_run').prefetch_related('course_run__course', 'course_run__course__partner')

        serializer = serializers.AffiliateWindowSerializer(seats, many=True)
        return Response(serializer.data)

course_discovery/apps/api/v1/views/catalogs.py
import datetime

from django.db import transaction
from django.http import HttpResponse
from dry_rest_permissions.generics import DRYPermissions
from rest_framework import status, viewsets
from rest_framework.decorators import detail_route
from rest_framework.response import Response

from course_discovery.apps.api import filters, serializers
from course_discovery.apps.api.pagination import ProxiedPagination
from course_discovery.apps.api.renderers import CourseRunCSVRenderer
from course_discovery.apps.api.v1.views import User
from course_discovery.apps.catalogs.models import Catalog
from course_discovery.apps.course_metadata.models import CourseRun


# pylint: disable=no-member
class CatalogViewSet(viewsets.ModelViewSet):
    """ Catalog resource. """

    filter_backends = (filters.PermissionsFilter,)
    lookup_field = 'id'
    permission_classes = (DRYPermissions,)
    queryset = Catalog.objects.all()
    serializer_class = serializers.CatalogSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    @transaction.atomic
    def create(self, request, *args, **kwargs):
        """ Create a new catalog. """
        data = request.data.copy()
        usernames = request.data.get('viewers', ())

        # Add support for parsing a comma-separated list from Swagger
        if isinstance(usernames, str):
            usernames = usernames.split(',')
            data.setlist('viewers', usernames)

        # Ensure the users exist
        for username in usernames:
            User.objects.get_or_create(username=username)

        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def destroy(self, request, *args, **kwargs):
        """ Destroy a catalog. """
        return super(CatalogViewSet, self).destroy(request, *args, **kwargs)

    def list(self, request, *args, **kwargs):
        """ Retrieve a list of all catalogs.
        ---
        parameters:
            - name: username
              description: User whose catalogs should be retrieved.
              required: false
              type: string
              paramType: query
              multiple: false
        """
        return super(CatalogViewSet, self).list(request, *args, **kwargs)

    def partial_update(self, request, *args, **kwargs):
        """ Update one, or more, fields for a catalog. """
        return super(CatalogViewSet, self).partial_update(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """ Retrieve details for a catalog. """
        return super(CatalogViewSet, self).retrieve(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        """ Update a catalog. """
        return super(CatalogViewSet, self).update(request, *args, **kwargs)

    @detail_route()
    def courses(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Retrieve the list of courses contained within this catalog.

        Only courses with at least one course run that can be enrolled in immediately,
        is ongoing or yet to start, and appears on the marketing site are returned.
        ---
        serializer: serializers.CatalogCourseSerializer
        """
        catalog = self.get_object()
        queryset = catalog.courses().available()
        course_runs = CourseRun.objects.active().enrollable().marketable()

        queryset = serializers.CatalogCourseSerializer.prefetch_queryset(
            queryset=queryset,
            course_runs=course_runs
        )

        page = self.paginate_queryset(queryset)
        serializer = serializers.CatalogCourseSerializer(page, many=True, context={'request': request})
        return self.get_paginated_response(serializer.data)

    @detail_route()
    def contains(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Determine if this catalog contains the provided courses.

        A dictionary mapping course IDs to booleans, indicating course presence, will be returned.
        ---
        serializer: serializers.ContainedCoursesSerializer
        parameters:
            - name: course_id
              description: Course IDs to check for existence in the Catalog.
              required: true
              type: string
              paramType: query
              multiple: true
            - name: course_run_id
              description: Course run IDs to check for existence in the Catalog.
              required: false
              type: string
              paramType: query
              multiple: true
        """
        course_ids = request.query_params.get('course_id')
        course_run_ids = request.query_params.get('course_run_id')

        catalog = self.get_object()
        courses = {}
        if course_ids:
            course_ids = course_ids.split(',')
            courses.update(catalog.contains(course_ids))

        if course_run_ids:
            course_run_ids = course_run_ids.split(',')
            courses.update(catalog.contains_course_runs(course_run_ids))

        instance = {'courses': courses}
        serializer = serializers.ContainedCoursesSerializer(instance)
        return Response(serializer.data)

    @detail_route()
    def csv(self, request, id=None):  # pylint: disable=redefined-builtin,unused-argument
        """
        Retrieve a CSV containing the course runs contained within this catalog.

        Only active course runs are returned. A course run is considered active if it is currently
        open for enrollment, or will be open for enrollment in the future.
        ---
        serializer: serializers.FlattenedCourseRunWithCourseSerializer
        """
        catalog = self.get_object()
        courses = catalog.courses()
        course_runs = CourseRun.objects.filter(course__in=courses).active().marketable()

        # We use select_related and prefetch_related to decrease our database query count
        course_runs = course_runs.select_related(*serializers.SELECT_RELATED_FIELDS['course_run'])
        prefetch_fields = ['course__' + field for field in serializers.PREFETCH_FIELDS['course']]
        prefetch_fields += serializers.PREFETCH_FIELDS['course_run']
        course_runs = course_runs.prefetch_related(*prefetch_fields)

        serializer = serializers.FlattenedCourseRunWithCourseSerializer(
            course_runs, many=True, context={'request': request}
        )
        data = CourseRunCSVRenderer().render(serializer.data)

        response = HttpResponse(data, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="catalog_{id}_{date}.csv"'.format(
            id=id, date=datetime.datetime.utcnow().strftime('%Y-%m-%d-%H-%M')
        )
        return response

course_discovery/apps/api/v1/views/organizations.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from course_discovery.apps.api import filters, serializers
from course_discovery.apps.api.pagination import ProxiedPagination


# pylint: disable=no-member
class OrganizationViewSet(viewsets.ReadOnlyModelViewSet):
    """ Organization resource. """

    filter_backends = (DjangoFilterBackend,)
    filter_class = filters.OrganizationFilter
    lookup_field = 'uuid'
    lookup_value_regex = '[0-9a-f-]+'
    permission_classes = (IsAuthenticated,)
    queryset = serializers.OrganizationSerializer.prefetch_queryset()
    serializer_class = serializers.OrganizationSerializer

    # Explicitly support PageNumberPagination and LimitOffsetPagination. Future
    # versions of this API should only support the system default, PageNumberPagination.
    pagination_class = ProxiedPagination

    def list(self, request, *args, **kwargs):
        """ Retrieve a list of all organizations. """
        return super(OrganizationViewSet, self).list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """ Retrieve details for an organization. """
        return super(OrganizationViewSet, self).retrieve(request, *args, **kwargs)

course_discovery/templates/publisher/course_run_detail/_all.html
{% load i18n %}

<div class="course-information" xmlns="http://www.w3.org/1999/html">

  <div class="info-item">
    <div class="heading">
      {% trans "Studio URL" %}
    </div>
    <div>
      {% if object.studio_url %}
        <a target="_blank" href="{{ object.studio_url }}">{{ object.lms_course_id }}</a>
      {% else %}
        {% trans "(Required) To be added by edX" %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Start Date (time in UTC)" %}
    </div>
    <div>{{ object.start }}</div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "End Date (time in UTC)" %}
    </div>
    <div>{{ object.end }}</div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Enrollment Track" %}
    </div>
    <div>{{ object.course_type }}</div>
  </div>

    {% if object.seat_price %}
      <div class="info-item">
        <div class="heading">
          {% trans "Certificate Price" %}
        </div>
        <div>
            ${{ object.seat_price }}
        </div>
      </div>
    {% endif %}

    {% if object.credit_seat_price %}
      <div class="info-item">
        <div class="heading">
          {% trans "Credit Price" %}
        </div>
        <div>
            ${{ object.credit_seat_price }}
        </div>
      </div>
    {% endif %}

  <div class="info-item">
    <div class="heading">
      {% trans "Course Staff" %}
    </div>
    <div>
      {% if not object.course_staff %}
        {% trans "(Required) Not yet added" %}
      {% else %}
        {% for obj in object.course_staff %}
          <div class="course-staff">
            <img src="{{ obj.image_url }}" alt=""/>

            <div class="staff-detail">
              <div class="name">
                  {% if obj.is_new %}
                    <span class="new-staff">{% trans "New" %}</span>
                  {% endif %}
                  <a href="#" class="btn-instructor-detail"  data-staff_id="{{ obj.uuid }}">{{ obj.full_name }}</a>
              </div>
              <div>{{ obj.position }}</div>
              <div class="organization">{{ obj.organization }}</div>
            </div>
          </div>
          <div class="clearfix"></div>
        {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Estimated Effort" %}
    </div>
    <div>
      {% if object.min_effort and object.max_effort %}
        {{ object.min_effort }}-{{ object.max_effort }} {% trans "hours per week" %}
      {% else %}
        {% with  object.estimated_effort as field %}
            {% include "publisher/_render_required_field.html" %}
        {% endwith %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Content Language" %}
    </div>
    <div>
      {% with  object.language.name as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Video Transcript Language" %}
    </div>
    <div>
      {% with  object.transcript_languages as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Video Language" %}
    </div>
    <div>
      {% with  object.video_language as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Length (Weeks)" %}
    </div>
    <div>
      {% with  object.length as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "MicroMasters Program Name" %}
    </div>
    <div>
      {% with  object.micromasters_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "XSeries Program Name" %}
    </div>
    <div>
      {% with  object.xseries_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Professional Certificate Program Name" %}
    </div>
    <div>
      {% with  object.professional_certificate_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

</div>
<div class="clearfix"></div>
<script type="text/javascript">
    var staffData = {{ course_staff_config | safe }};
</script>

course_discovery/templates/publisher/course_run_detail/_cat.html
{% load i18n %}
{% block content %}

   <div class="course-information">
        <div class="info-item">
            <div class="heading">
                {% trans "Course ID" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy">
              {% with  object.lms_course_id as field %}
                {% include "publisher/_render_required_field.html" %}
              {% endwith %}
            </div>
        </div>
        <div class="info-item">
            <div class="heading">
                {% trans "Enrollment Types" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy">{{ object.course_type|capfirst }}</div>
        </div>
    </div>



    {% include 'publisher/course_run_detail/_seats.html' %}
    {% include 'publisher/course_run_detail/_credit_seat.html' %}

    <div class="clearfix"></div>

{% endblock %}

course_discovery/templates/publisher/course_run_detail/_clipboard.html
<button class="btn btn-small btn-copy" title="Copy to clipboard" aria-label="Copy to clipboard">
    <span class="icon fa fa-copy" aria-hidden="true"></span>
</button>

course_discovery/templates/publisher/course_run_detail/_edit_warning.html
{% load i18n %}

<div id="editCourseRun" class="modal">
    <div class="modal-content">
        <h2 class="hd-2 emphasized">
            <span class="icon fa fa-exclamation-triangle" aria-hidden="true"></span> {% trans "CAUTION" %}
        </h2>
        <span class="sr-only">CAUTION</span>
        <p>
<!-- Is "tasawer" in line 12 correct? -->
            {% blocktrans trimmed with owner=object.course_run_state.owner_role reviewer_user='tasawer'%}
                The {{ current_team_name }} is currently reviewing this course run. If you edit course run information, you might overwrite the team’s changes, and you will have to send the course run to the {{ team_name }} for review again.
            {% endblocktrans %}
        </p>
        <div class="actions">
            <a class="btn-cancel closeModal" href="#">{% trans "Cancel" %}</a>
            <a class="btn-brand btn-base btn-accept" type="button" href="{% url 'publisher:publisher_course_runs_edit' object.id %}">{% trans "Edit" %}</a>
        </div>
    </div>
</div>

course_discovery/templates/publisher/course_run_detail/_widgets.html
{% load i18n %}

<div class="course-widgets">
    {% if can_edit %}
        {% url 'publisher:publisher_course_runs_edit' pk=object.id as edit_page_url %}
        <a href="{% if add_warning_popup %}#{% else %}{{ edit_page_url }}{% endif %}" class="btn btn-neutral btn-courserun-edit">
            {% trans "EDIT" %}
        </a>
        <div class="clearfix"></div>
    {% endif %}
    <div class="approval-widget {% if not publisher_approval_widget_feature %}hidden{% endif %}">
        {% include 'publisher/_approval_widget.html' %}

        <div id="decline-comment" class="hidden clearfix">
            {% trans 'Reason for declining preview' as decline_reason %}
            {% trans 'Submit' as submit %}
            {% include 'comments/add_auth_comments.html' with comment_type='decline_preview' box_label=decline_reason btn_label=submit %}
        </div>
        {% include 'publisher/course_run_detail/_preview_accept_popup.html' %}

        {% if add_warning_popup %}
            {% include 'publisher/course_run_detail/_edit_warning.html' %}
        {% endif %}
    </div>
</div>

course_discovery/templates/publisher/course_run_detail/course_run_detail.html
{% extends 'publisher/base.html' %}

{% load compress %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans "Course Run Details" %}
{% endblock title %}

{% block page_content %}
<div class="layout-1t2t layout-flush publisher-container course-detail">
    <main class="layout-col layout-col-b layout-col-b-custom">
        {% if object.course_run_state.is_published %}
            <div class="depth depth-0 published-status">
                <strong>
<!-- Is it possible to make "View it on edx.org" into a link? If so, make it into a link, add a period at the end, and delete "at". If not, keep "at", but remove the colon and add a period after the link. -->
                    {% blocktrans with publish_date|date:'m/d/y' as course_publish_date trimmed %}
                        The About page for this course run was published on {{ course_publish_date }}.
                    {% endblocktrans %}
                    {% if object.preview_url %}
                        {% trans "View it on edx.org at" %}
                    {% endif %}
                </strong>
                {% if object.preview_url %}
                    <a href="{{ object.preview_url }}" target="_blank">{{ object.preview_url }}</a>
                {% endif %}
            </div>
        {% endif %}
        <nav class="administration-nav">
            <div class="tab-container">
                {% if can_view_all_tabs %}
                    <button class="selected" data-tab="#tab-1">{% trans "All" %}</button>
                    {% comment %}Translators: Studio is an edX tool for course creation.{% endcomment %}
                    <button data-tab="#tab-2">{% trans "STUDIO" %}</button>
                    {% comment %}Translators: CAT is an acronym for Course Administration Tool.{% endcomment %}
                    <button data-tab="#tab-3">{% trans "CAT" %}</button>
                    {% comment %}Translators: DRUPAL is an edX marketing site.{% endcomment %}
                    <button data-tab="#tab-4">{% trans "DRUPAL" %}</button>
                    <button data-tab="#tab-5">Salesforce</button>
                {% endif %}
            </div>
        </nav>

        <div id="app">
            <div class="page-header">
                <h2 class="hd-2 emphasized">
                    <span class="course-name">{{ object.title }}</span>
                </h2>
            </div>

            {% include 'alert_messages.html' %}

            <div id="stateChangeAlert" class="alert-messages hidden">
                <div class="alert alert-error" role="alert" tabindex="-1">
                    <div>
                        <p id="stateChangeError" class="alert-copy"></p>
                    </div>
                </div>
            </div>

            <div class="tabs">
                <div id="tab-1" class="tab-content active">
                    {% include 'publisher/course_run_detail/_all.html' %}
                </div>
              {% if can_view_all_tabs %}
                <div id="tab-2" class="tab-content">
                    {% include 'publisher/course_run_detail/_studio.html' %}
                </div>
                <div id="tab-3" class="tab-content">
                    {% include 'publisher/course_run_detail/_cat.html' %}
                </div>
                <div id="tab-4" class="tab-content">
                    {% include 'publisher/course_run_detail/_drupal.html' %}
                </div>
                <div id="tab-5" class="tab-content">
                    {% include 'publisher/course_run_detail/_salesforce.html' %}
                </div>
              {% endif %}
            </div>
        </div>
    </main>

    <aside id="right-panel" class="layout-col layout-col-a layout-col-a-custom">
        <div id="approval-widget" class="approval-widget {% if not publisher_approval_widget_feature %}hidden{% endif %}">
        {% with is_course_run=True %}
          {% include 'publisher/course_run_detail/_widgets.html' %}
        {% endwith %}
        </div>
        <div id="comments-widget" class="comment-container {% if not publisher_comment_widget_feature %}hidden{% endif %}">
            {% include 'comments/add_auth_comments.html' with comment_type='default' %}
            {% include 'comments/comments_list.html' %}
        </div>
    </aside>
</div>
{% include 'publisher/course_run_detail/_instructor_profile.html' %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'bower_components/clipboard/dist/clipboard.min.js' %}"></script>
    <script src="{% static 'js/publisher/jquery-dateFormat.min.js' %}"></script>
    <script src="{% static 'js/publisher/views/course_detail.js' %}"></script>
    <script src="{% static 'js/publisher/organizations.js' %}"></script>
    <script src="{% static 'js/publisher/comments.js' %}"></script>
    <script src="{% static 'js/publisher/course-tabs.js' %}"></script>
    <script src="{% static 'js/publisher/preview-url.js' %}"></script>
    <script src="{% static 'js/publisher/change-state.js' %}"></script>
    <script src="{% static 'js/publisher/modal-screen.js' %}"></script>
    <script>
        new Clipboard(".btn-copy", {
            text: function(trigger) {
                return $(trigger).parent().next('.copy').html().trim();
            }
        });
    </script>
{% endblock %}